// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGd9aYdTT7PiyFT5qGtByDjrZKcSR9IZc',
    appId: '1:607326716970:web:WEBAPPID',
    messagingSenderId: '607326716970',
    projectId: 'mailchat-5b6a8',
    authDomain: 'mailchat-5b6a8.firebaseapp.com',
    storageBucket: 'mailchat-5b6a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGd9aYdTT7PiyFT5qGtByDjrZKcSR9IZc',
    appId: '1:607326716970:android:9abdfcf626bab1dc83ef53',
    messagingSenderId: '607326716970',
    projectId: 'mailchat-5b6a8',
    storageBucket: 'mailchat-5b6a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGd9aYdTT7PiyFT5qGtByDjrZKcSR9IZc',
    appId: '1:607326716970:ios:IOS_APP_ID',
    messagingSenderId: '607326716970',
    projectId: 'mailchat-5b6a8',
    iosBundleId: 'com.example.mailchat',
    storageBucket: 'mailchat-5b6a8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGd9aYdTT7PiyFT5qGtByDjrZKcSR9IZc',
    appId: '1:607326716970:ios:IOS_APP_ID',
    messagingSenderId: '607326716970',
    projectId: 'mailchat-5b6a8',
    iosBundleId: 'com.example.mailchat',
    storageBucket: 'mailchat-5b6a8.firebasestorage.app',
  );
}
